### ISSUE TITLE
$ ln -nfs ruote ruote-kit/vendor/ruote not OK, 

### ISSUE THREAD

**Issue by jmettraux** [kennethkalmer/ruote-kit#1]
stuck with "Expecting vendor/ruote to exist"

```
$ ln -s ../../ruote ruote-kit/vendor/
```

instead ?

**Comment by kennethkalmer** [comment]
Doc tlc (closed by 564c78521d494c955dbdca0c191022c315aa8353)

**Comment by kennethkalmer** [comment]
Thanks, did update the README and updated the initializer to be more verbose when failing to detect vendor/ruote (See 564c785)
