### ISSUE TITLE
404 resource not found

### ISSUE THREAD

**Issue by northox** [kennethkalmer/ruote-kit#10]
Hi guys,

I getting some issues while integrating ruote-kit using "rake rails:template LOCATION=https://github.com/tosch/ruote-kit/raw/master/rails-template.rb".

When I launch a process (i.e. the default with alice and bob) I get a message saying "process launched" but when I click on the link to see the actual process I get this message: "404 resource not found".

Any idea?

**Comment by jmettraux** [comment]
Hello,

what is the exact URI of the link that goes 404 ?
Any error [+ backtrace] in the console 'during' the 404 ?
Any issues when running "rake rails:template" ?

**Comment by northox** [comment]
http://0.0.0.0:3000/_ruote/processes/20110401-pazabuge
no errors logged

<pre>
<code>
$ rake rails:template --trace
(in /home/northox/svnwork/x)
** Invoke rails:template (first_time)
** Execute rails:template
rake aborted!
can't convert nil into String
/usr/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/tasks/framework.rake:25:in `expand_path'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/tasks/framework.rake:25
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
</code>
</pre>

**Comment by jmettraux** [comment]
Many thanks for the further info. I have "forwarded" the issue to Torsten's fork which is the official (http://ruote.rubyforge.org/source.html).

We'll fix them ASAP (monday somehow) and close them both.

https://github.com/tosch/ruote-kit/issues#issue/5

**Comment by tosch** [comment]
I tried hard, but sorry, I can't reproduce that issue, neither using Rails 3.0.5 nor 3.0.3, neither using Ruby 1.9.2-p180 nor REE 2011.03.

The backtrace gives no hint there is anything wrong with our Rails template, so it's really hard to debug from here.

**Comment by northox** [comment]
Hum, I guess it has something to do with with my gems versions. I retried from scratch and still get the same problem. 

Here's the step that I took:

```
  $ rails new test -m https://github.com/tosch/ruote-kit/raw/master/rails-template.rb
  $ cd test
  $ bundle install
  $ rails s
  (got some complaint about json)
  $ cat 'gem "json"' >> Gemfile
  $ rails s
  got it running
  clicked on launch process
  clicked launch and get "<h1>Process launched<h1> process /_ruote/processes/20110414-boguyujeho has been launched."
  but when I click the link I get "<h1>404 resource not found</h1> <a href="javascript:history.go(-1)">back</a>" (this is not a dump it's in the normal ruote-kit template)
```

see: http://www.mantor.org/~northox/misc/Screenshot.png

I can't find anything relevant in the logs.

Feels like nothings get saved/launched. Hope this help.

**Comment by tosch** [comment]
Sorry, still cannot reproduce that issue.

Which ruby version do you use? Which Rails version did you use for your latest test?

When having launched a process, is there a directory "ruote_work_development" in Rails.root?

If there is, what happens when you launch

```
  rake ruote:run_worker
```

in another terminal?

**Comment by northox** [comment]
ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
Rails 3.0.5

Yes there is. Here's the content: http://pastebin.com/X9P3Fbzk

The run_worker command does not return and print no errors messages. Seems to be working.

Here's my gem list: http://pastebin.com/EKWLZ6Qg

**Comment by tosch** [comment]
> Yes there is.

So there seems to be a problem with the worker.

> The run_worker command does not return and print no errors messages. Seems to be working.

Please check if you still get the 404 when the worker is running.

I will try to setup a similar environment to yours tomorrow, but I don't know if I'll find the time.

**Comment by northox** [comment]
Yes I still get the 404.

Much appreciated.

**Comment by tosch** [comment]
> Yes I still get the 404.

Either there is a problem with the worker or with the participant registration. Hmm. Building an env with 1.8.7-p249 now.

Could you please post the files engine.json and participant_list.json somewhere under configurations in the ruote work dir?

**Comment by tosch** [comment]
Ok, I can reproduce the problem using Ruby 1.8.7-p249. Will investigate.

**Comment by tosch** [comment]
It's a problem with the *****\* json gem.

I'd suggest to use the excellent yajl-ruby instead. Instead of

```
gem "json"
```

use

```
gem "yajl-ruby", :require => "yajl"
```

in your Gemfile before the ruote stuff. That should be a work around, but unfortunately, it's not a fix. There should be no need to mention a json lib in the Gemfile at all. I will look into that, but it'll take some time, can't afford high priority on that, sorry.

**Comment by tosch** [comment]
Ok, I was faster than I thought initially. Ruote requires a json lib (yajl-ruby OR json OR json_pure OR json-jruby). Ruby 1.9.2 ships with one, apparently, Ruby 1.8.7 not.

Rails has its own fallback json implementation (somewhere under) ActiveSupport::JSON that could be used. Let's see what @jmettraux says on that.

**Comment by northox** [comment]
Thanks a lot Tosch! Everything's working great.

**Comment by jmettraux** [comment]
@tosch thanks a lot !
