### ISSUE TITLE
make ruote-kit compatible with compass and sass

### ISSUE THREAD

**Issue by fvanclef** [kennethkalmer/ruote-kit#11]
Hello, 

I am using the compass gem for stylesheet management. Because the ruote-kit request the 3.0.25 haml gem version, I have an error when rails is starting saying that the declare method is missing. I have modified the ruote-kit gemspec 

  s.add_runtime_dependency('haml', '3.0.25') unless defined?(Bundler)

to overwrite if necessary the haml version for my particular project.

Best regards

Frédéric

**Comment by jmettraux** [comment]
Hello Frédéric,

have you tried in your explorations with a more recent version of haml (3.1.2 for example) ?

```
s.add_runtime_dependency('haml', '3.1.12')
```

Maybe it solves the issue.

John

**Comment by jmettraux** [comment]
(if it solves the issue, I will update the Gemfile)

**Comment by fvanclef** [comment]
Hello John,

I have tested with the 3.1.1 version of haml and it is working well. This is
the current official version for haml.

There is also a edge version I have not tested yet. Today the version is
3.1.79-edge but I prefer to wait for a final release.

I have also another question about json library.

I am using jruby and it seems that the json-jruby or the json-pure are not
working anymore. I am receiving that error when I modify a workitem and save
it.

ArgumentError - wrong number of arguments (2 for 1):
 json/ext/GeneratorState.java:187:in `generate'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/json-jruby-1.4.3.1-universal-java-1.6/lib/json/common.rb:212:in
`generate'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/rufus-json-1.0.1/lib/rufus/json.rb:37:in
`Json'

The yajl-ruby gem is not an option because of jruby. What I had to do is to
force the backend version via the Rufus::Json.load_backend('active_support')
command and it is working now. It is fine for me, maybe other jruby user
will be interested by this info.

Thanks

Best regards

Frdric

Frdric

**Comment by tosch** [comment]
Hi Frédéric,

since June 7th, 3.1.2 is the official haml version available. I updated the gemspec accordingly and hope it works with your application.

Thanks for the hint,
Torsten

**Comment by jmettraux** [comment]
Hello Frédéric,

so json-ruby 1.4.3.1 is not working, understood.
What version of json-pure is not working ?

Thanks in advance,

John

**Comment by fvanclef** [comment]
Hello Torsten,

Thanks for the information, the haml web site is not up to date. I have
installed the last gem and it is working perfectly !

Best regards

Frdric

**Comment by fvanclef** [comment]
Hi John,

Actually it is the json-1.5.1-java that gives a problem.

NoMethodError - undefined method `merge' for
#<JSON::Ext::Generator::State:0x636064>:
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/json/encoding.rb:61:in
`options_for'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/json/encoding.rb:46:in
`encode'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/json/encoding.rb:77:in
`check_for_circular_references'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/json/encoding.rb:45:in
`encode'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/json/encoding.rb:30:in
`encode'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/activesupport-3.0.7/lib/active_support/core_ext/object/to_json.rb:20:in
`to_json'
 json/ext/GeneratorState.java:193:in`generate'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/json-1.5.1-java/lib/json/common.rb:212:in
`generate'
 c:/dev/jruby-1.6.2/lib/ruby/gems/1.8/gems/rufus-json-1.0.1/lib/rufus/json.rb:37:in
`Json'

Thanks

Best regards

Frdric

**Comment by jmettraux** [comment]
OK, I couldn't reproduce the issue.

I have tested with

activesupport (3.0.8)
bouncy-castle-java (1.5.0146.1)
jruby-openssl (0.7.4)
json (1.5.1 java)
json_pure (1.5.1)
rake (0.9.2)
rdoc (3.6.1)

jruby-1.6.2 installed via rvm 1.6.20 on Snow Leopard.

Next time please report the issue directly at https://github.com/jmettraux/rufus-json/issues

I'd also suggest taking part in the mailing list if you want to keep multiple issue reports in one thread. It's at http://groups.google.com/group/openwferu-users

Thanks again,

John
