### ISSUE TITLE
handle process with nil root expression

### ISSUE THREAD

**Issue by iamer** [kennethkalmer/ruote-kit#13]
I am facing a lot of errors in ruote-kit  handling of processes without root expression
One way of reaching this state is launching this process :

```
Ruote.process_definition :name => 'test', :revision => '0.1' do
  sequence do
    do_flanked :flank => true
    wait '30s'
    error
  end
  define 'do_flanked' do
    cursor do
      listen :to => :errors
      echo "error"
      rewind
    end
  end
end
```

Then waiting for error to happen, then DELETE the error (in effect reapplying the expression)

To get the process list page to render I needed :

https://github.com/MeeGoIntegration/ruote-kit/commit/af36afad7124309d849d7da03984f1f3f760370a

on top of latest HEAD

as well as

https://github.com/MeeGoIntegration/ruote/commit/5adb5617ff65f6b4538ff353edd7ac6c03ffca6d

There are more places that need fixing as well

Thanks Richard (github user amtep) for helping.

**Comment by jmettraux** [comment]
So, you have fixed the symptoms but left the cause intact.

I don't understand this commit:

  https://github.com/MeeGoIntegration/ruote-kit/commit/af36afad7124309d849d7da03984f1f3f760370a

It's an incomplete copy of my commit:

  https://github.com/kennethkalmer/ruote-kit/commit/95d7bd34142c8bd2a8da4f543bd8ba1e39e2c3aa

The ruote commit looks OK, I won't merge it until I was dealt with the cause.

Please note that your process definition is better written:

```
Ruote.process_definition :name => 'test', :revision => '0.1' do
  sequence :on_error => 'handle_error' do
    wait '30s'
    error
  end
  define 'handle_error' do
    echo "error"
  end
end
```

**Comment by iamer** [comment]
that commit is needed in addition to your commit as in this pull request :

https://github.com/kennethkalmer/ruote-kit/pull/14/commits

There is also another way to reach this state using :forget , but I still can't reproduce it reliably

**Comment by iamer** [comment]
the idea of the flanked process is to only notify about the error not handle it. In your process the error would go away and I won't be able to reapply at the point it happened. Isn't that right or am I misunderstanding ?

**Comment by jmettraux** [comment]
It's right.

Maybe engine#on_error could help here.

  http://ruote.rubyforge.org/configuration.html#engine_on

**Comment by iamer** [comment]
Interesting that's a very nice way to notify the ruote administrator :)

The flanked subprocess works well to notify someone responsible as configured _ per process _

Thanks for all the help.

**Comment by jmettraux** [comment]
Hello,

I packaged your process definition into:

  https://gist.github.com/1476176

and ran it.

The final line indicates that the root_expression is not nil.

How can I reproduce the issue ?

Cheers,

John

**Comment by iamer** [comment]
After the error happens you need to delete it. In ruote-kit I clicked the DELETE button in the error details page.

**Comment by jmettraux** [comment]
Ah, sorry, my bad, you had already specified that in the initial report. I will rework my test case.

**Comment by jmettraux** [comment]
Fix is at:

  https://github.com/jmettraux/ruote/commit/0722b658c59a4ad246707c49eb76b4eca84b3dd3

Feel free to re-open this issue if the fix isn't OK.

Many thanks !

John
