### ISSUE TITLE
:timers support

### ISSUE THREAD

**Issue by northox** [kennethkalmer/ruote-kit#19]
Hello,

Is it possible that ruote-kit does not support the :timers attribute? http://ruote.rubyforge.org/common_attributes.html#timers

The following process will trigger an error but will work if I remove the :timers attribute.

<pre><code>
pdef = Ruote.define :name => 'issue_mgmt', :revision => '1' do
  concurrence :wait_for => 'admin' do
    administrator :tag => 'admin', :timers '1m: reminder_soon, 2m: reminder_final, 3m:reminder_late'
    evaluator
  end
end
</code></pre>

Here's the error log.

<pre><code>NoMethodError - undefined method `sid' for nil:NilClass:
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:33:in `block (2 levels) in singletonclass'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:26:in `each'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:26:in `block in singletonclass'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:65529:in `instance_eval'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:65529:in `singletonclass'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/views/schedules.html.haml:65527:in `__tilt_34900320'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/tilt-1.3.3/lib/tilt/template.rb:140:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/tilt-1.3.3/lib/tilt/template.rb:140:in `cached_evaluate'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/tilt-1.3.3/lib/tilt/template.rb:127:in `evaluate'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/tilt-1.3.3/lib/tilt/haml.rb:24:in `evaluate'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:636:in `render'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-respond_to-0.8.0/lib/sinatra/respond_to.rb:138:in `render'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:532:in `haml'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/helpers/misc_helpers.rb:12:in `block (2 levels) in respond_with'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-respond_to-0.8.0/lib/sinatra/respond_to.rb:196:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-respond_to-0.8.0/lib/sinatra/respond_to.rb:196:in `respond_to'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/helpers/misc_helpers.rb:11:in `respond_with'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/bundler/gems/ruote-kit-9d653ea84c6d/lib/ruote-kit/resources/schedules.rb:13:in `block in <class:Application>'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `block in compile!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (3 levels) in route!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (2 levels) in route!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `catch'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in `block in route!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `route!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/methodoverride.rb:24:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/static.rb:53:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/logger.rb:15:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/head.rb:9:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/methodoverride.rb:24:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:82:in `optimized_each'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/routing/route_set.rb:538:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/sass-3.1.19/lib/sass/plugin/rack.rb:54:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/etag.rb:23:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/conditionalget.rb:25:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/head.rb:14:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/flash.rb:243:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/session/abstract/id.rb:195:in `context'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/session/abstract/id.rb:190:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/cookies.rb:331:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/activerecord-3.1.6/lib/active_record/query_cache.rb:64:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/activerecord-3.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.1.6/lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.1.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/reloader.rb:68:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/sendfile.rb:101:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.1.6/lib/rails/rack/logger.rb:13:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/methodoverride.rb:24:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/runtime.rb:17:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/activesupport-3.1.6/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/lock.rb:15:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/actionpack-3.1.6/lib/action_dispatch/middleware/static.rb:61:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.1.6/lib/rails/engine.rb:456:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.1.6/lib/rails/application.rb:143:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/content_length.rb:14:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/railties-3.1.6/lib/rails/rack/log_tailer.rb:14:in `call'
    /home/northox/.rvm/gems/ruby-1.9.3-p194@global/gems/rack-1.3.6/lib/rack/handler/webrick.rb:59:in `service'
    /home/northox/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
    /home/northox/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /home/northox/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
</code></pre>

**Comment by jmettraux** [comment]
Yes, seems like it. I will fix that as soon as possible.

**Comment by northox** [comment]
No problem, no rush. I would have happily submitted a patch but I'm still not very comfortable with Ruote/Ruote-kit. One day I'll make it up to you.

**Comment by jmettraux** [comment]
Hopefully it's fixed. If not, please re-open this issue.

Many thanks!

John
