### ISSUE TITLE
Update readme, following instructions results in broken installation right now

### ISSUE THREAD

**Issue by bluehallu** [kennethkalmer/ruote-kit#20]
Because the readme forces an old version of ruote-kit:

```
gem 'ruote-kit', '~> 2.2.0'
```

following the instructions as they come makes you run into this:

https://github.com/kennethkalmer/ruote-kit/issues/17

**Comment by jmettraux** [comment]
Many thanks!

Feel free to re-open it with further details if that doesn't fix it.
