### ISSUE TITLE
Update rails-template, following instructions results in broken installation right now

### ISSUE THREAD

**Issue by bluehallu** [kennethkalmer/ruote-kit#21]
Can't reopen the last issue I opened, basically the same bug is inside the template on:

https://raw.github.com/tosch/ruote-kit/master/rails-template.rb

**Comment by jmettraux** [comment]
Hello Torsten,

would you have some time to look at this one (in the README.rdoc I point at the masters instead of ~> 2.2.0, I think we should do it as well in the template).

Please tell if you don't have the time and I'll do it tomorrow morning.

Cheers,

John

**Comment by bluehallu** [comment]
I just removed any version restriction from the Gemfile and it works. If I use the master:

Updating git://github.com/jmettraux/ruote.git
Fetching git://github.com/kennethkalmer/ruote.git
remote: Counting objects: 16744, done.
remote: Compressing objects: 100% (4537/4537), done.
remote: Total 16744 (delta 12296), reused 16410 (delta 12105)
Receiving objects: 100% (16744/16744), 3.41 MiB | 161 KiB/s, done.
Resolving deltas: 100% (12296/12296), done.
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

**Comment by tosch** [comment]
Thanks for the issue report.

Note that there's an issue with Rails 3.2.7 at the moment, I hope to have a solution for that soon.

**Comment by jmettraux** [comment]
Many thanks to you guys!

**Comment by tosch** [comment]
Fixed the issue with the current Rails version as well.
