### ISSUE TITLE
Dependent Gem versions causing problems?

### ISSUE THREAD

**Issue by henry74** [kennethkalmer/ruote-kit#29]
I'm getting some strange behavior when I try and include ruote-kit in my Gemfile.  I'm using Padrino 0.11.0 and when I add ruote-kit to the Gemfile, it drops back to an earlier version of Padrino.  I"m guessing this is due to a ruote-kit dependency on an earlier version of Sinatra.

Any ideas how I can troubleshoot this?

Thanks,
Henry

**Comment by jmettraux** [comment]
Hello,

you could fork ruote-kit and point your Gemfile to that fork. Then play with the dependencies in your fork's Gemfile or ruote-kit.gemspec. Another variant would be to force dependencies in your Gemfile before ruote-kit gets included in it.

> I'm guessing this is due to a ruote-kit dependency on an earlier version of Sinatra.

Not sure about that, ruote-kit.gemspec says `s.add_runtime_dependency 'sinatra', '>= 1.2.0'` on master.

Play with the Gemfile to see what Bundler yields.

Best regards,
