### ISSUE TITLE
better error message when error in process definition

### ISSUE THREAD

**Issue by jmettraux** [kennethkalmer/ruote-kit#3]
(I don't if I should fill the issue here or in Torsten's fork, anyway...)

When there is an error in the process definition, the ugly default error screen is shown. Could instead the input screen be reshown with the "flash" containing the error message ?

Keep up the great work !

**Comment by tosch** [comment]
I think here is OK as it's the main repo and mine is just a fork.

**Comment by tosch** [comment]
Have a look at tosch@1ea4d0bd8762035b7bebf6876bbcb8a48efa741c

I'm just catching ArgumentErrors as they are the only ones I'm sure I may get when calling Ruote::Engine#launch. Doing a "wildcard" catch just doesn't seem right to me.

**Comment by jmettraux** [comment]
closing.
