### ISSUE TITLE
RuoteKit config in config.ru doesn't start worker

### ISSUE THREAD

**Issue by jmettraux** [kennethkalmer/ruote-kit#4]
http://gist.github.com/332586
http://ruote.rubyforge.org/irclogs/ruote_2010-03-15.txt (starting 0614 UTC)

There is no worker, thus no workflow execution.

Note that running from rails3 (http://gist.github.com/332599) works fine (weird)

**Comment by tosch** [comment]
Should be solved with the latest release (http://github.com/kennethkalmer/ruote-kit/tree/v2.1.8.2), there is a worker bound to the engine now if configuration.run_worker is true
