### ISSUE TITLE
Ruote-kit middleware suppresses rails exception stacktrace 

### ISSUE THREAD

**Issue by rebo** [kennethkalmer/ruote-kit#5]
When i use

```
    config.middleware.use 'RuoteKit::Application'
```

any rails errors show up as "Internal Server Error" in the browser even in development mode.  A tempory fix is to override RuoteKit / Sinatra's defaults and set

```
RuoteKit::Application::set(:show_exceptions,true)
```

but this is a bit hacky and shows a Sinatra formatted stacktrace and not a rails one.

**Comment by tosch** [comment]
best solution for rails3: http://github.com/tosch/ruote-on-rails/commit/758144abcd3c6675e82a198f001e5105e0d7d5e3

**Comment by tosch** [comment]
Ok, this seems to be a problem only in Rails 3, Rails 2 shows the usual exception screens.

As there are different ways to use RuoteKit (standalone or as Rack app), this issue won't be addressed in RuoteKit itself.

I don't think using

<pre>RuoteKit::Application::set(:show_exceptions,true)</pre>

is hacky, though. It's the preferred way to change configuration vars. Just note that you should use

<pre>RuoteKit::Application::set(:raise_errors, true)</pre>

to get Rails' exception pages back. The solution in tosch/ruote-on-rails@758144abcd3c6675e82a198f001e5105e0d7d5e3 is better in the way that RuoteKit's (=Sinatra's) routing will only be bothered for its own routes.
