### ISSUE TITLE
Invalid gemspec with ruote-kit v2.2.0

### ISSUE THREAD

**Issue by codeblogger** [kennethkalmer/ruote-kit#9]
Hi there,

the latest release (v2.2.0) contains an invalid gemspec which results in error statements (see below) when using RubyGems:

> $ gem list
> 
> Invalid gemspec in [/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/specifications/ruote-kit-2.2.0.gemspec]: Illformed requirement ["#YAML::Syck::DefaultKey:0x107e25f60 1.0"]

**Comment by tosch** [comment]
Oh great. Thought I double-checked that. I'm on it, thanks for the report and sorry for the inconvenience.

**Comment by jmettraux** [comment]
( linking to https://github.com/tosch/ruote-kit/issues/4 )

**Comment by jmettraux** [comment]
fixed (for me) with https://rubygems.org/gems/ruote-kit/versions/2.2.0.2.

Please re-open if the issue persists (or mutates somehow).

Many thanks for reporting !

**Comment by codeblogger** [comment]
Many thanks for fixing.
